### PR TITLE
Add conversions to insights streams

### PR DESCRIPTION
**Pull request by GtheSheep**
# Description of change
Include schemas for conversions in insights tables
Remove duplicate "reach" in schema of ads_insights

# Manual QA steps
 - Running this tap daily and comparing to values in Meta ads insights manager
 
# Risks
 - Any unexpected formats of conversions on various API versions? But can't see any obvious changes
 
# Rollback steps
 - revert this branch

### CODE REVIEW

**Comment by beauchbum** [comment]
Hi @GtheSheep, checking if this is still in progress? Looking forward to this getting merged so we can leverage conversions data. Thanks!

**Comment by GtheSheep** [comment]
Hey @beauchbum - I've been running this off my fork for a couple of months now and all seems well, not sure what else is required to get this merged other than for someone to review?

**Comment by GtheSheep** [comment]
@dsprayberry @luandy64 @kethan1122 - not sure what the process is to get this reviewed, any insight plz?

**Comment by sgandhi1311** [comment]
@GtheSheep thanks for your contribution. I will review the change and get it deployed.

**Review by sgandhi1311 — APPROVED** [review]

**Comment by sgandhi1311** [comment]
@GtheSheep @beauchbum, the PR changes have been deployed to production. Could you verify on your end? Thank you!

**Pull request merged**
